# site title
title: Mosaice's Blog

# user name or organization name
user: mosaice

# issue repository
repository: Blog

# multi-author
authors:

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 5#08d7587e84679d4f66a57030c83ed359cccde51

# posts per page
perpage: 10


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'UPDATED_AT'
